PR #30342: [XLA:GPU] Update Bazel command to run presubmit for oneAPI
Imported from GitHub PR https://github.com/openxla/xla/pull/30342

The XLA Linux x86 GPU oneAPI presubmit job is failing with the following error:

ERROR: No test targets were found, yet testing was requested.

Since the hermetic build currently supports only running the XLA build, and running the test cases requires Intel hardware, the Bazel command is being changed from bazel test to bazel build

Copybara import of the project:

--
acac86f2b391b0aa113b47b345227b925fa7020a by mraunak <mayank.kumar.raunak@intel.com>:

Update build.py
--
3886154009201a663b1ffee8798dad2d7e4dea3a by mraunak <mayank.kumar.raunak@intel.com>:

Fix the pre-submit failure

Merging this change closes #30342

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/30342 from Intel-tensorflow:mraunak/presubmit_build 3886154009201a663b1ffee8798dad2d7e4dea3a
PiperOrigin-RevId: 796730101