Pass HERMETIC_PYTHON_URL in python_register_toolchains as a single URL.
The old logic is faulty as it treats the protocol prefix as a valid URL.

The `base_url` and the relative URL are
concatenated back together somewhere deep in Bazel code.\
It is clearly done in a way where extraneous slashes are stripped from the connecting ends of each fragment, and then, expectedly so, concatenated with a single slash. \
This results in the URL being `http:/fake-download.com/my-python.tar.gz`.\
It then promptly fails to download the file due to the URL being malformed, failing like so:

```
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'requirements.bzl': no such package '@@pypi//': no such package '@@python_3_14_host//': no such package '@@python_3_14_x86_64-unknown-linux-gnu//': java.io.IOException: Error downloading [https:/storage.googleapis.com/general-ml-ci-transient/jax-github-actions/jax/CI%20-%20Free-threading%20and%20Thread%20Sanitizer%20%28nightly%29/589/1/python-tsan.tgz] to /__w/.cache/bazel/bazel/_bazel_root/a40625930fdef4f0a3483cd60aa1bb86/external/python_3_14_x86_64-unknown-linux-gnu/temp6087362296404491585/python-tsan.tgz: Connection refused
```
PiperOrigin-RevId: 842839120